### ISSUE TITLE
How to render html

### ISSUE THREAD

**Issue by darekmeco** [luwes/sinuous#10]
Hi how to render html in string
something like  dangerouslySetInnerHTML in react or v-html in vue ?
Thanks.

**Comment by luwes** [comment]
Sinuous will in most cases set the defined attributes in the view as element properties so a simple `innerHTML="<p>Hello</p>"` like the native JS element property will work.

See here for a little example: https://codesandbox.io/s/sinuous-innerhtml-z6k71

Thanks for your question, you can leave this issue open in case someone else is wondering the same.
