### ISSUE TITLE
New example project: plain SPA

### ISSUE THREAD

**Issue by johannschopplich** [luwes/sinuous#100]
Hey there!

What a great library to work with. I've created a small boilerplate to pair sinuous and storeon router, which tie together quite nicely.
Repository: https://github.com/johannschopplich/plain-spa
Demo: https://plain-spa.jhnn.dev/

I've incorporated the sinuous todo app for demonstration purposes.

The project runs in your browser without any bundling, but can be bundled if wanted (including htm to hyperscript compiling).

I'd love to add it to the example list. Does it fit your requirements?

**Comment by luwes** [comment]
wow thanks @johannschopplich! this is awesome!
yes, for sure. I'll add your project to the readme very soon

**Comment by johannschopplich** [comment]
I'm glad to hear that! Thanks for adding the project. 🙂
