### ISSUE TITLE
[property.js] replace String.slice() with String.startsWith()

### ISSUE THREAD

**Issue by leeoniya** [luwes/sinuous#103]
@luwes 

https://github.com/luwes/sinuous/blob/0791cf98eda1ed2c9f2aae193ab2db7efb9e804d/packages/sinuous/h/src/property.js#L21-L22

https://caniuse.com/#search=startsWith

i've seen significant gains with avoiding string slicing/allocation. especially in a hot path like prop name testing.

the same can be done in `on*` testing, but it already avoids slicing, so the gains here is likely noise-level.

https://github.com/luwes/sinuous/blob/0791cf98eda1ed2c9f2aae193ab2db7efb9e804d/packages/sinuous/h/src/property.js#L9

however, would not support IE11 out of the box, but is easily shimmed.

**Comment by leeoniya** [comment]
an equally efficient solution that's ie-compatible is lastIndexOf:

https://stackoverflow.com/a/4579228

**Comment by luwes** [comment]
thanks @leeoniya! I didn't do much testing around this, good you brought it up. 
yes, I prefer less polyfills for IE if possible. `lastIndexOf` could be good

**Comment by luwes** [comment]
seems not really worth it and it adds 8 bytes because slice is used in a bunch of places (gzip). https://jsperf.com/test-vs-indexof-fast/6

**Comment by leeoniya** [comment]
interesting, i did a less trivial test and the results are still surprising. in chrome on my machine indexOf wins and lastIndexOf is last. in firefox lastIndexOf is faster. oddly, neither browser is faster for startsWith(). unless i got something wrong:

https://jsperf.com/test-vs-indexof-fast/8

**Comment by ryansolid** [comment]
I remember testing this specifically a while back and slice being the fastest in chrome. All the index based ones were slower and I replaced them. I originally used startsWith. That no longer seems the case though. I want to say it wasn't that long ago like in the summer or fall. Like maybe Chrome 75/76 time period.

**Comment by luwes** [comment]
for me too

<img width="983" alt="Screen Shot 2020-04-26 at 10 15 59 PM" src="https://user-images.githubusercontent.com/360826/80383857-25337500-8872-11ea-9908-aea15039ed86.png">

**Comment by leeoniya** [comment]
on my z5 compact startsWith is ahead of slice but no by that much!

weird, i figured slice/substring has to allocate mem but startWith/indexOf should not. :shrug: 

![Screenshot_20200427-095346_1](https://user-images.githubusercontent.com/43234/80387243-07641100-886e-11ea-9c28-41606c995c09.png).
