### ISSUE TITLE
Sinuous Map broken?

### ISSUE THREAD

**Issue by theSherwood** [luwes/sinuous#104]
Hi @luwes,
Is the sinuous-map example from the website broken on the more recent releases of sinuous? I'm getting a crash when sinuous is updated to 0.27.0. [Sandbox](https://codesandbox.io/s/sinuous-map-k8yzb)

**Comment by luwes** [comment]
map should be a named import I think. 
Not a default

**Comment by theSherwood** [comment]
Oh. right. Of course. Sorry about that.

**Comment by luwes** [comment]
all good :)
