### ISSUE TITLE
JSX Types don't allow for observables to be passed in to values like htm does

### ISSUE THREAD

**Issue by Brecert** [luwes/sinuous#105]
Example:
```tsx
import { h, o } from 'sinuous'
const val = o('')
const App = <div>
  <input onInput={e => o(e.currentTarget.value)} />
  <input value={val} />
</div>
```
Gives the type error:
```error
Type 'Observable<any>' is not assignable to type 'string | number | string[] | undefined'.
  Type 'Observable<any>' is missing the following properties from type 'string[]': pop, push, concat, join, and 25 more.

(JSX attribute) JSXInternal.HTMLAttributes<HTMLInputElement>.value?: string | number | string[] | undefined
```
Even though the generated code functions as expected (as far as I can tell), there are type errors.
I changed this behavior in my [fork](https://github.com/Brecert/sinuous/commit/e51e049ec6f87813caba24529806dad5510f6a76), but it feels a little hacky the way I did it.

**Comment by luwes** [comment]
thanks for reporting @Brecert. ah yes, I see.
makes sense, the types were mostly adapted from Preact.

yes, there might be a simpler solution. I'll look into this soon

**Comment by luwes** [comment]
thanks again, I had no idea how to fix this myself so your changes were added to master!
