### ISSUE TITLE
Polyfill for IE11

### ISSUE THREAD

**Issue by gkn06** [luwes/sinuous#107]
What is the recommended polyfill for Array.from()?

[MDN polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill) is not working as expected.

**Comment by luwes** [comment]
I've used this one with success in the test suite
https://polyfill.io/v3/polyfill.min.js?features=Array.from

also easy site to choose polyfills https://polyfill.io/

**Comment by gkn06** [comment]
Thanks @luwes I will try that. 
Am just curious why MDN polyfill fails? Do you know why?

**Comment by luwes** [comment]
not so sure, I'll look into this soon. I'm surprised it doesn't work
