### ISSUE TITLE
global data store ?

### ISSUE THREAD

**Issue by darekmeco** [luwes/sinuous#11]
Hi, What is proper way to share data between components? In vue, react there are state stores, but I dont want to use external libraries for it ? I think I should make global data container  for it. But im not sure what is proper way. Thanks

**Comment by luwes** [comment]
Good question @darekmeco. typically this can be done through passing props from parent to child. it's explained in the docs here https://sinuous.netlify.com/main-concepts/components/

Or do you mean more something like Redux?

**Comment by pynnl** [comment]
You can use observable I guess.
https://stackblitz.com/edit/js-7npnhv
