### ISSUE TITLE
This lib has won me over

### ISSUE THREAD

**Issue by mrjjwright** [luwes/sinuous#118]
Building something fun and that I love with this.  Thank you for this pure little lib, it's so flexible.

**Comment by luwes** [comment]
thank you @mrjjwright, I appreciate it! post the result here if it's finished, would love to see

**Comment by mrjjwright** [comment]
![image](https://user-images.githubusercontent.com/4343/86304867-6ecf7180-bbcd-11ea-9d22-e9bb52520d01.png)
