### ISSUE TITLE
onAttach/onDetach component lifecycle add-on

### ISSUE THREAD

**Issue by heyheyhello** [luwes/sinuous#121]
Hey I just finished publishing these. Let me know if they're working/intuitive enough to be put into the community list in your readme. No rush 🌺. I could also develop a dedicated showcase application to show it off if it'd be helpful.

- https://www.npmjs.com/package/sinuous-lifecycle
- https://www.npmjs.com/package/sinuous-trace

Together they're about 1kb. The monorepo is at https://gitlab.com/nthm/sinuous-packages/ or https://github.com/heyheyhello/sinuous-packages

I also updated the demo page: https://nthm.gitlab.io/stayknit/ which uses the packages with their optional log package to write into the browser console

**Comment by luwes** [comment]
Awesome @heyheyhello! will definitely add these to the readme list, thanks for putting these together!

**Comment by heyheyhello** [comment]
🎉
