### ISSUE TITLE
How to use sinuous like next.js ssr?

### ISSUE THREAD

**Issue by kethan** [luwes/sinuous#128]
Can anybody throw me an idea of how to use sinuous like next.js is being used?

A very simple example would be helpful.

Thanks.

**Comment by kethan** [comment]
any help appreciated?

**Comment by theSherwood** [comment]
@kethan What do you mean by "like next.js is being used"? Are you referring to SSR or some other aspect of Nextjs?

**Comment by kethan** [comment]
> yes, this is not one of Sinuous's goals. I never tried SSR and I don't see any amazing benefits of using it honestly. there are so many server side template languages that are great and build for outputting html server side.
> 
> I'm a big fan of https://www.11ty.dev/ which keeps the choice open in what template language you like to output HTML. https://sinuous.dev/ is build with it as well, see the source here https://github.com/luwes/sinuous-site/
> 
> In combination with `sinuous/hydrate` this works pretty well!
> 
> Another example using Sinuous hydrate with heavy state use is this demo page of Playerx.
> https://dev.playerx.io/demo/
> 
> I'm quite fond of this pattern where you just make snippets of HTML dynamic.
> https://github.com/playerxo/playerx/blob/master/packages/playerx-demo/src/js/demo.js

Ok, thank you. I will have a look
