### ISSUE TITLE
Problems running the test-suite

### ISSUE THREAD

**Issue by mindplay-dk** [luwes/sinuous#129]
I've been trying to run the test-suite and didn't have any luck.

After `npm install` and `npm run test`, it does run some tests, but then exits with this error:

```
...
✓ cache key should be unique
✓ do not mutate spread variables
✓ ignore HTML comments
# tests 205
# pass  205
✓ ok
Done in 1.13s.
08 08 2020 15:29:20.785:ERROR [config]: Error in config file!
  Error: Cannot find module 'rollup-plugin-babel'
Require stack:
- /mnt/c/workspace/sinuous/karma.conf.js
- /mnt/c/workspace/sinuous/node_modules/karma/lib/config.js
- /mnt/c/workspace/sinuous/node_modules/karma/lib/server.js
- /mnt/c/workspace/sinuous/node_modules/karma/lib/cli.js
- /mnt/c/workspace/sinuous/node_modules/karma/bin/karma
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/mnt/c/workspace/sinuous/karma.conf.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
```

I noticed in `package.json` in `devDependencies` you've listed `@rollup/plugin-babel`, which appears to be a newer package than the [imported](https://github.com/luwes/sinuous/blob/bd0bda1c15afde9092ce48affb8447134f94a804/karma.conf.js#L6) package `rollup-plugin-babel` - so I tried updating the import, and this causes the test to run to the same point as before:

```
...
✓ cache key should be unique
✓ do not mutate spread variables
✓ ignore HTML comments
# tests 205
# pass  205
✓ ok
Done in 1.15s.
```

But instead of exiting with an error, it stalls at that point and doesn't exit at all.

I figured maybe it's entered watch mode? But changing a file doesn't seem to trigger anything.

I'm on WSL2 on Windows btw.

**Comment by luwes** [comment]
thanks for reporting, that seems my bad. yes, that should be the fix 👍 
it'll go in watch mode indeed. add `--single-run` for a one off test.

**Comment by mindplay-dk** [comment]
Hmm, if I run it with `npm run test -- --single-run`, it finishes, but exits with status code 1.

Even though there are no failed tests, as far as I can tell. 🤔

It looks like it's trying to run more tests though, after the first batch, but looks like it's not finding them?

```
...
✓ cache key should be unique
✓ do not mutate spread variables
✓ ignore HTML comments
# tests 205
# pass  205
✓ ok
Done in 1.13s.
# tests 0
# pass  0
✓ ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sinuous@0.0.0 test: `cross-env COVERAGE=true yarn test:htm && karma start --single-run "--single-run"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sinuous@0.0.0 test script.
```

That last bit with `# tests 0` doesn't display when run without the `--single-run` flag - it would seem, in watch mode, something is blocking the other tests, and in single-run mode, those tests aren't working?

Sorry, I don't know enough about these tools to fix it...

**Comment by mindplay-dk** [comment]
Confirmed, works for me now. Thanks! 🙂👍

### To others on Windows (WSL2)

You can run the browser tests against your Windows native Chrome installation - use a command like:

    export CHROME_BIN='/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe'

(depending on your local Chrome installation path.)

Then launch the test and explicitly select Chrome for the browser-dependent tests:

    npm run test -- --browsers=Chrome

Note that, if your working folder is on a Windows drive, you will need to launch with the `--single-run` switch, because watching files for changes, on a Windows drive, from Linux, does not currently work in WSL2. I recommend you use a working folder on the emulated Linux file-system, e.g. in your home-folder `~/somewhere` as opposed to `/mnt/c/somewhere` - testing continuously (in watch mode, the default for this test-suite) will work, and performance is in the order of 20-60 times higher.
