### ISSUE TITLE
Event assignment doesn't work in templates

### ISSUE THREAD

**Issue by MotorHeat** [luwes/sinuous#130]
Very good and nice library :)
I find a small bug. Check the below code.
Expected: when user press button alert should appear
Actual: nothing happens

```JavaScript
import { observable, h } from "sinuous";
import { template, t, o } from 'sinuous/template';

const ButtonTemplate = template( () => h('div', 
      h('button', {onclick: o('buttonClick')}, 'Click me')
    )
);

let buttonClick = observable(() => { 
  alert('first click');
  buttonClick( () => alert('another handler!'));
})

let app = ButtonTemplate({ buttonClick: buttonClick })
document.body.append( app );

```

Same behavior with `t` instead `o`

This happens because `api.property` does't call event handler and relevant action is not recorded in `template.js`

I am not sure how to fix this to support observables

**Comment by luwes** [comment]
Thanks for the bug report, this is fixed 🎉 
https://codesandbox.io/s/hungry-cloud-3wuc0?file=/src/index.js
