### ISSUE TITLE
Hydrate: broken example

### ISSUE THREAD

**Issue by mindplay-dk** [luwes/sinuous#134]
The [documentation for hydrate](https://sinuous.dev/docs/hydrate/) links to [this sandbox](https://codesandbox.io/s/sinuous-hydrate-xbzu6), which didn't work.

I don't think there's such a thing as a PR on CSB (?) but here's [a fixed fork of the sandbox](https://codesandbox.io/s/sinuous-hydrate-forked-0ob35?file=/src/index.js) - you can just copy/paste from `index.js` and press the "update" button in your list of dependencies.

(it was a bad import, that's all.)

**Comment by luwes** [comment]
thanks @mindplay-dk! updated the codesandbox
