### ISSUE TITLE
Unnecessary observable reads when reading from a computed value

### ISSUE THREAD

**Issue by heyheyhello** [luwes/sinuous#139]
Hey small question, I'm trying to understand this snippet of code:

https://github.com/luwes/sinuous/blob/97e7f866219fd819b4bf60c044f1f71585160ed3/packages/sinuous/observable/src/observable.js#L185-L195

Is the first conditional block only for the case when a comp (A) uses another comp (B), so then B is to give all of its observables to A? If so then should those observables only be read when tracking is true?

```js
  function data() {
    if (update._fresh) {
      if (tracking) { // ➕ Like this
        update._observables.forEach(o => o());
      }
    } else {
      value = update();
    }
    return value;
  }
```

I made the change and it passes all the tests. I wonder if it's done this way for bundle size? One less conditional to include in code at the expense of more runtime calls? I suppose most observables (computed or not) are read when `tracking` is true...

Thanks!

**Comment by luwes** [comment]
thanks for the feedback! I think you're right, that condition can be safely added.

I didn't do it on purpose for bundle size I believe.

do you know of a use case where this would make a big difference?
it's mostly related to `sample` and using many `computed`'s I'm thinking

**Comment by heyheyhello** [comment]
For me it was event listeners. Maybe I shouldn't do that and/or be more mindful of using computeds. I have a `<canvas />` `mousemove` event listener that was determining when a user enters a different region of the canvas - but the canvas can be resized, so I decided to code the boundaries as computeds and do checks like:

```ts
canvas.addEventListener('mousemove', ev => {
    const c = evToGridCoord(ev);
    // This is an o()
    hoverThrottled(`(${ev.offsetX}, ${ev.offsetY}) ➡ (${c.x}, ${c.y})`);
    if (c.x > canvasGridWidth() / 2) { // This is a computed()
      // in second half of canvas width
    }
    // ... etc (a few other boundary checks using other computeds)
```

But really I should probably use `let canvasGridWidth;` (etc) variables and then have buttons that change the canvas dimensions update the `let` variables instead of using observables/computeds... Then it's just a variable and not a (series of) function calls, which might be more important for mousemove events that fire every few frames.

**Comment by luwes** [comment]
you're totally right, it should be as-cheap-as-possible. good call! 
I'll add it in soon or if you have some bandwidth I'll review the PR 👍

**Comment by artalar** [comment]
Hi there! I'm not investigating it deeply, but here the problem reproduce: https://codesandbox.io/s/sinuous-observable-forked-9gpzd?file=/src/index.js

**Comment by heyheyhello** [comment]
Observable subscriptions can be confusing but the behaviour in the codesandbox is correct. It looks like you're expecting it to execute the minimum set of computed but actually _all_ computeds will be called when an observable updates - they're not lazy.

By writing:
```js
const fullName = computed(
  () => console.log("fullName") || `${firstName()} ${lastName()}`
);
```
You're saying "any time firstName _or_ lastName changes, call fullName. This happens even if the result of fullName isn't used by anything. There's some similar concern about observable disposal (https://github.com/luwes/sinuous/issues/115#issuecomment-643748127) where you want to be lazy and not do work unless required...

Here's your sandbox modified to not have the unnecessary call: https://codesandbox.io/s/sinuous-observable-forked-64o1d but this doesn't exactly mean it's "better" because now you're doing the work of unsubscribing/disposing the computed and then making a _new_ one and linking it all up...each time, so, its a bit of a "pick you poison".
