### ISSUE TITLE
`template` inserts with duplicate value are empty

### ISSUE THREAD

**Issue by luwes** [luwes/sinuous#14]
Noticed there was an issue with inserts that have the same value.
https://codesandbox.io/s/sinuous-template-issue-t3o57

Probably because of 

https://github.com/luwes/sinuous/blob/a105a1e0a4adaca9e82b918e296cf069d2c8995b/packages/sinuous/h/src/insert.js#L9-L9

**Comment by dyu** [comment]
I was about to file an issue with this problem (discovered this last week). Great job with sinuous btw :-)
