### ISSUE TITLE
Typescript: DocumentFragment should be a valid JSX element

### ISSUE THREAD

**Issue by DrSensor** [luwes/sinuous#147]
work fine when transforming using esbuild but got an error when type checked
```tsx
const
  DocFrag = () => h([
    <span>fragment</span>
  ]),
  jsx = <DocFrag />,        // 👈ERROR
  out = h(DocFrag, null)
```
```ts
const DocFrag: () => DocumentFragment
'DocFrag' cannot be used as a JSX component.
  Its return type 'DocumentFragment' is not a valid JSX element.
    Type 'DocumentFragment' is missing the following properties from type
```

**Comment by heyheyhello** [comment]
The JSX typings have `JSXInternal.Element` set to an interface that only extends `HTMLElement` but it should be `type Element = HTMLElement | SVGElement | Node`. Can you apply this to your `node_modules/sinuous/jsx.d.ts` (maybe reload your editor) and then report back if this fixes the issue? Then either you or I can open a PR if it fixes things for you.

![image](https://user-images.githubusercontent.com/44614862/99755343-63f37b80-2a9f-11eb-8022-3d773f108e7d.png)
