### ISSUE TITLE
computed() superfluous?

### ISSUE THREAD

**Issue by quixot1c** [luwes/sinuous#154]
In your docs there is an example including a `computed` value:

```
import { observable, computed, subscribe } from 'sinuous/observable';

const length = observable(0);
const squared = computed(() => Math.pow(length(), 2));

subscribe(() => console.log(squared()));
length(4); // => logs 16
```

When thinking about it I was wondering whether the computed was needed at all, since `subscribe` creates a reactive context and `squared` uses an `observable` and then is converted into one itself (if I understand correctly and also didn't mix some concepts with those of `solid` which I also have been looking at :P). When trying the code with `const squared = () => Math.pow(length(), 2);` it still works.

So what is the use case for `computed()`?

**Comment by heyheyhello** [comment]
Computed is a cache. It saves the result of its function and will avoid doing work if its observables haven't changed.

It's not a big deal for your example, but if the `squared` function was replaced with something expensive to compute then it's only computed once for many calls.

**Comment by quixot1c** [comment]
Thanks for your response. Is the difference between `computed` and `memo` from https://github.com/luwes/memo that `memo` takes function arguments into consideration as well?

**Comment by heyheyhello** [comment]
Oh sorry, yes I think that's correct but I haven't actually had a use for memo at all. I believe the code is very short though if you're still curious
