### ISSUE TITLE
`map` using object equality causes re-renders

### ISSUE THREAD

**Issue by AndersCan** [luwes/sinuous#163]
_I've only recently started to learn Sinuous, so I might be doing something wrong here._

I'm rendering a list of objects with `map` and all items seem to always get re-rendered. I've debugged it and think I've found the reason why: diff.js is using object equality https://github.com/luwes/sinuous/blob/master/packages/sinuous/map/src/diff.js#L31 

My list of objects is created from a `computed` function that generates new objects each call.

<details>
  <summary>Example of re-rendering</summary>

Working from the example from: https://sinuous.dev/docs/lists/, I've extended it with a `computedList` that shows my problem as it will always re-render.
```js
import { o, html } from "sinuous";
import { computed } from "sinuous/observable";
import { map } from "sinuous/map";

const list = o([
  { id: 1, text: "bread" },
  { id: 2, text: "milk" },
  { id: 3, text: "honey" },
  { id: 4, text: "chips" },
  { id: 5, text: "cookie" },
]);

const computedList = computed(() => {
  return list().map((element) => {
    return { id: element.id };
  });
});

const view = () => html`
  <ul>
    <li>Efficient renders</li>
    ${map(list, (item) => html` <li id=${item.id}>${item.text}</li> `)}
  </ul>
`;

const computedView = () => html`
  <ul>
    <li>Always re-renders</li>
    ${map(computedList, (item) => html` <li>${item.id}</li> `)}
  </ul>
`;

document.body.append(view());
document.body.append(computedView());

setInterval(() => {
  list([...list().sort(() => Math.random() - 0.5)]);
}, 1000);
```

I think I could solve the issue above, if I simply make the `computedList` a string array.
```js
const computedList = computed(() => {
  return list().map((element) => {
    return element.id;
  });
});
```
This works fine in this example, but not so much in my App :sweat_smile: 
</details>

Would it make sense if `map` could accept a `key` prop that it could use to determine if two objects are equal? Perhaps something similar to what React does: https://reactjs.org/docs/lists-and-keys.html#keys

**Comment by luwes** [comment]
good question, it's indeed how you thought, it's based on object equality and since the map in computedList always creates new objects the rendering will be fully cleared first and re-rendered.

there's nothing like the key prop in Sinuous but it's easy to implement with something like 
https://github.com/luwes/memo but if you really want the minimal amount of code it's also possible to use a local cache based on the id.


```js
const cached = memo((id) => { id });

const computedList = computed(() => {
  return list().map((element) => {
    return cached(element.id);
  });
});
```

```js
const cached = {};

const computedList = computed(() => {
  return list().map((element) => {
    return cached[element.id] || (cached[element.id] = { id: element.id });
  });
});
```

didn't test but something like this should work

**Comment by AndersCan** [comment]
Thanks for the quick reply. I've gone ahead and implemented your second example (local cache) and now things are working as expected.

I'll go ahead and close this issue, but maybe `object equality` should be mentioned on https://sinuous.dev/docs/lists/?
