### ISSUE TITLE
Lazy component cleanup not working.

### ISSUE THREAD

**Issue by kethan** [luwes/sinuous#181]
Here I have a component and when I remove that component it doesn't invoke the cleanup function. Need help.

Here is the code:
https://codesandbox.io/s/sinuous-lazy-cleanup-notworking-3st9x?file=/src/index.jsx

**Comment by heyheyhello** [comment]
I see `F Cleanup..` in the console, can you describe the issue in more detail? It makes sense that `cleanup` is binding to the `() => show() ...` computed.

**Comment by heyheyhello** [comment]
Oh but this behaviour is weird... are you seeing this in your DOM?

```
loading...
Hello sinuous
```

I feel like you want that loading text to have disappeared? Not really sure why it sticks around but if I give it a more specific mounting node it works:

```diff
const lazy = (file) => {
  const content = o();
  return (props) => {
    content(props && props.fallback);
    file().then((f) => {
      content(f.default(props));
    });
-    return content;
+   return h([], content); // or `return <p>{content}</p>`
  };
};
```

**Comment by kethan** [comment]
> Oh but this behaviour is weird... are you seeing this in your DOM?
> 
> ```
> loading...
> Hello sinuous
> ```
> 
> I feel like you want that loading text to have disappeared? Not really sure why it sticks around but if I give it a more specific mounting node it works:
> 
> ```diff
> const lazy = (file) => {
>   const content = o();
>   return (props) => {
>     content(props && props.fallback);
>     file().then((f) => {
>       content(f.default(props));
>     });
> -    return content;
> +    return h([], content); // or `return <p>{content}</p>`
>   };
> };
> ```

Oh yeah, that actually fixes the text disappearance. Now the issue is when the dynamic component is unloaded or removed from the DOM it doesn't not trigger cleanup I don't know why .

**Comment by luwes** [comment]
@kethan sorry for the late reply. the `cleanup` function has to be called synchronous with the `subscribe` functions which are called internally. Only then is there a `tracking` context on which cleanups can be collected. See here for the code.
https://github.com/luwes/sinuous/blob/8da017729f46b4f7aabe50f6d129a2b9e27d3157/packages/sinuous/observable/src/observable.js#L198-L200

I think the best way is to pass a cleanupFn as a prop and re-set it in the lazy/async component. See this example:
https://codesandbox.io/s/sinuous-lazy-cleanup-notworking-forked-dy03s?file=/src/hello.jsx

**Comment by kethan** [comment]
ok, thanks.
