### ISSUE TITLE
Update demos with custom reactive library

### ISSUE THREAD

**Issue by fabiospampinato** [luwes/sinuous#185]
Hello there, the demos using S.js and hyperactiv [here](https://github.com/luwes/sinuous/wiki/Choose-your-own-reactive-library) don't seem to be working, sinuous doesn't seem to have a default export and looking at the types I don't see anywhere a function like the one used in the demos that accepts a "subscribe" function.

Possibly the API changed since those demos were last updated.

Could they be updated?

**Comment by luwes** [comment]
Thanks for reporting @fabiospampinato and providing the wiki update @heyheyhello ! 
Updated the examples https://github.com/luwes/sinuous/wiki/Choose-your-own-reactive-library
