### ISSUE TITLE
Live Fragment Issue

### ISSUE THREAD

**Issue by skethan** [luwes/sinuous#205]
I am having issues if I update the view with fragments.
Eg: https://stackblitz.com/edit/vitejs-vite-uj6g1b?file=main.jsx

**Comment by heyheyhello** [comment]
This isn't an issue with Sinuous - it's how document fragments work: https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment#usage_notes says:

> [It's common to] insert the fragment into the DOM using [Node](https://developer.mozilla.org/en-US/docs/Web/API/Node) interface methods such as [appendChild()](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild), [append()](https://developer.mozilla.org/en-US/docs/Web/API/Element/append), or [insertBefore()](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore). Doing this moves the fragment's nodes into the DOM, leaving behind an empty DocumentFragment.

Note that Sinuous will silently append items of arrays so `<div>{[1,2,3]}</div>` is `<div>1 2 3</div>` (as text nodes in this case). This means `<>{n}</>` will create a document fragment and then _append each element of `n`_ into it, which empties the fragments (see above MDN quote).

You can see this in your browser console:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/44614862/188686627-3e21d793-a930-4b27-9422-6346bca1e568.png">

The first log, before rendering, shows items in the fragment. Immediately after calling `<App/>`, those fragments are now empty.

**Comment by kethan** [comment]
@heyheyhello yes thanks i understood.
