### ISSUE TITLE
<textarea> does not keep "readonly" attribute

### ISSUE THREAD

**Issue by rozek** [luwes/sinuous#216]
the following example

```
  document.body.appendChild(
    html`<textarea readonly>(should be readonly)</textarea>`
  )
```

creates a textarea element which is NOT readonly

**Comment by rozek** [comment]
surprisingly,

```
  let Textarea = html`<textarea readonly>(readonly)</textarea>`
    Textarea.readonly = true
  document.body.appendChild(Textarea)
```

does not work either

**Comment by luwes** [comment]
thanks for the feedback, Sinuous sets properties by default so it should be `readOnly` I believe.
for setting attributes directly you can also use `<textarea attrs="${{ readonly: '' }}"></textarea>`
https://github.com/luwes/sinuous/blob/527eb4ac67f3cce126c1dd2bbe5ea54c580fae1a/src/h/src/property.js#L34-L37

**Comment by rozek** [comment]
great!

Indeed, I had to write "readOnly" instead of "readonly"!

Sorry for bothering you - and thanks for the quick response!

**Comment by Frenzoid** [comment]
Close the issue please :)
