### ISSUE TITLE
semantics of "subscribe" function parameter?

### ISSUE THREAD

**Issue by rozek** [luwes/sinuous#219]
By looking into `map` I found that the function argument for `subscribe` may have an (undocumented) parameter - what is the semantic of this parameter?

**Comment by luwes** [comment]
could you link to the code line? not seeing it right away. thanks

**Comment by rozek** [comment]
map.js, line 28:

```javascript
  const unsubscribe = subscribe((a) => {
```

what is the meaning of `a`?

**Comment by luwes** [comment]
oh yes, that's the previous list of items. it's what is returned in the callback.

**Comment by rozek** [comment]
ah, I see, thanks.

Might be useful enough to be documented...
