### ISSUE TITLE
Bug: string objects will not be rendered

### ISSUE THREAD

**Issue by rozek** [luwes/sinuous#220]
the following minimal example

```
  let x = 'x', X = new String('x')
  document.body.appendChild(html`
    Primitive: ${x}, Object: ${X}
  `)
```

will properly render the string primitive, but not the string object

**Comment by heyheyhello** [comment]
Have you tried isolating this to htm specifically? https://github.com/luwes/sinuous/blob/main/src/htm.js is borrowed from developit's htm repo.

**Comment by rozek** [comment]
no, I haven't isolated the problem - it just caused problems in my application

**Comment by heyheyhello** [comment]
```js
typeof x === "string"
typeof X === "object"
```
It's as simple as that :/ The `h()` reviver has to be fast and make quick decisions. Less branches the better. It's not a very common usecsse to need to support string objects, so checking manually every single dom operation (read h.js) seems unnecessarily wasteful.

**Comment by rozek** [comment]
I see...

...and since the problem with string objects occurred when I had to repair the `map` function and is gone now, I can probably live with that restriction.

It should, however, be mentioned in the docs...

(and, yes, I agree with you that the introduction of primitives with the need for boxing and unboxing was a terrible design decision in JavaScript)
