### ISSUE TITLE
Question: recommendation for animations

### ISSUE THREAD

**Issue by rozek** [luwes/sinuous#228]
Is there any common recommendation how to implement transitions (i.e., animations while components get mounted or unmounted) and explicit animations with sinuous?

I'm not talking about CSS animations which appear when CSS settings have changed.

The use cases I have in mind are more like

* application pages which slide in/out
* new DOM elements fading in or out
* list and list item animations when lists get sorted

and so on

**Comment by luwes** [comment]
no sorry, Sinuous is pretty low level. it's all left up to the user.
