### ISSUE TITLE
Computed / Triggering a function

### ISSUE THREAD

**Issue by andymans** [luwes/sinuous#25]
Suppose I have:

```
const strings = {
    'en': {'greeting': 'Good Morning'},
    'de': {'greeting': 'Guten Morgen'}
}
```

And an observable variable:

`const lang = o('en')
`
And a function:

```
const i18n = (key) => {
    return strings[lang()][key]
}
```

Next,  a cpl visual components:

`<p>${lang}</p>`

`<h4>${i18n('greeting')}</h4>
`
And lastly a button:

`<button onclick=${()=> lang('de')}>Switch Lang</button>
`

When I click the button the lang variable does indeed change (the p element is rendered), but the i18n function that powers the h4 element is not re-evaluated. Any ideas?

**Comment by andymans** [comment]
doh!

The answer is that the computed in the h4 MUST be a function call:

`<h4>${() => i18n('hello')}</h4>
`

I'll leave this here in case someone else comes across the same issue

**Comment by luwes** [comment]
if you want it even cleaner it's possible to make the i18n function return another function.

```js
const i18n = (key) => {
    () => return strings[lang()][key]
}
```

```js
<h4>${i18n('hello')}</h4>
```

that should work too

**Comment by andymans** [comment]
Nice!
