### ISSUE TITLE
Hydration method

### ISSUE THREAD

**Issue by luwes** [luwes/sinuous#26]
Would be great to be able to "hydrate" DOM trees that are generated statically by the server or a static site generator aka HTML from a HTML file.

**Comment by tomByrer** [comment]
Hoping for this, either for local-dev build-tool (Rollup etc) & for 'edge' severless serving, eg [CloudFlare Workers](https://github.com/tomByrer/awesome-cloudflare-workers).  (Though in the case with CloudFlare, the server is an actual web browser tab, though I don't know if they removed the DOM in their monkey-patching Chromium.)

**Comment by luwes** [comment]
Hydration support was added in v0.15.0 🎉
