### ISSUE TITLE
How to use object in observable

### ISSUE THREAD

**Issue by kethan** [luwes/sinuous#30]
Hi,

How can I use an object in o?

Eg. https://jsfiddle.net/kethan/52a1q47x/9/

**Comment by luwes** [comment]
@kethan this should do it https://jsfiddle.net/luwes/hLptc30o/

behind the scenes all single observables like `${name}` are wrapped in a closure.
they expand to something like `${() => name()}`. 
for any calculations or function wrapping it's required to go to this long form with the closure visible.

hope this helps.

**Comment by kethan** [comment]
Perfect!.

**Comment by kethan** [comment]
How to use the counter variable c?

```js
<script type="module">
import { o, html } from "https://unpkg.com/sinuous?module";

function Profile() {
  const s = o({
  	c: 0
  });
  return html`
  <div>
    <button onclick=${() => s().c-- }>-</button>
    ${() => s().c}
   <button onclick=${() => s().c++ }>+</button>
   </div>
  `;
}

document.body.append(
  html`
    ${Profile()}
    ${Profile()}
    ${Profile()}
  `
);
</script>
```

**Comment by luwes** [comment]
see here https://swiss.netlify.com/fixtures/renderers/sinuous/
you'll have to `set` the new value w/ `s(s().c++)`

**Comment by kethan** [comment]
I tried. https://jsfiddle.net/kethan/f8u712kz/15/ not working

**Comment by luwes** [comment]
sorry, I was mistaken. you have re-set an object so like this https://jsfiddle.net/luwes/dj1buLs9/

`s({ c: s().c - 1 })`

**Comment by kethan** [comment]
yeah. thank you.
