### ISSUE TITLE
Usage of Props (No Issue)

### ISSUE THREAD

**Issue by kethan** [luwes/sinuous#31]
Hi,
Wow, such an amazing library I started to love it already. And the size of the library is impressive.
This not an issue actually.

I have been using Hyperapp (https://github.com/jorgebucaran/hyperapp). So I did a similar imitation of it. But I don't know how to use props in app() function.

Eg: https://codesandbox.io/s/sinuous-counter-krlz2

**Comment by luwes** [comment]
Thanks for the kind words @kethan, I appreciate it!

I added some examples to the readme which could help with that.
https://github.com/luwes/sinuous/#examples

Here in the docs it is explained a little
https://sinuous.netlify.com/main-concepts/components/

**Comment by kethan** [comment]
Yeah I check it but I want to send props separately

**Comment by kethan** [comment]
Yeah thank you.
