### ISSUE TITLE
Usage with script tag?

### ISSUE THREAD

**Issue by kethan** [luwes/sinuous#35]
I am getting Uncaught ReferenceError: o is not defined

```js
<!DOCTYPE html>
<html lang="en">

<head>
</head>

<body>
  <script src="https://unpkg.com/sinuous"></script>
<script>
const counter = o(0);
const view = () => {
    return html`
    <div>Counter ${counter}</div>
  `;
};

document.body.append(view());
setInterval(() => counter(counter() + 1), 1000);
</script>
</body>
</html>
```

**Comment by luwes** [comment]
@kethan with just a script tag the `observable` and `htm` script will also have to be added.

`https://unpkg.com/sinuous/dist/observable.js`
`https://unpkg.com/sinuous/dist/htm.js`

example here https://codesandbox.io/s/sinuous-counter-urb1p

also the props are set on the `sinuous` object; `sinuous.html` and `sinuous.o`.

**Comment by kethan** [comment]
Thank you. It's working
