### ISSUE TITLE
Cloning Observable Object

### ISSUE THREAD

**Issue by kethan** [luwes/sinuous#38]
Hi,

```js
let s = {
  count: o(0)
};
```
ex: https://codesandbox.io/s/swiss-test-uj3e2

How do I clone s to a new object?

**Comment by luwes** [comment]
@kethan sorry for the late reply. Cloning the object `s` would be:

```js
let s = {
  count: o(0)
};
let s2 = Object.assign({}, s);
```

Note that `s.count` is a really a function so it is passed by reference not by value.

If you like to make a new copy/clone of `s.count` with the current value it would be something more like:


```js
function cloneObservableObject(obj) {
	const newObj = {};
	for (let prop in obj) {
		const ob = obj[prop];
		newObj[prop] = o(ob());
	}
	return newObj;
}

let s2 = cloneObservableObject(s);
```

Hope this helps.

**Comment by kethan** [comment]
Yes, Thank you.

**Comment by kethan** [comment]
Modified to fit nested object and normal functions

```js
function cloneObject(obj) {
  var clone = {};
  for (var prop in obj) {
    if (obj[prop] != null && typeof obj[prop] === "object")
      clone[prop] = cloneObject(obj[prop]);
    else {
      const ob = obj[prop];
      if (typeof ob === "function" && ob.name === "i") clone[prop] = o(ob());
      else clone[prop] = ob;
    }
  }
  return clone;
}
```

```js
let s2 = {
  c: {
    count: o(0),
    s1: 3,
    log: () => console.log("hi"),
    ret: () => 5
  }
};
```

**Comment by luwes** [comment]
just be careful with `ob.name === "i" || ob.name ==="data"` 
`i` is the minified name I imagine but this can change from build to build, it's what the JS minifier chooses at build time. 

The observable function also has a `.$o` prop set to true. It's safer to use . that I think.
https://github.com/luwes/sinuous/blob/529d718f1132929c3001c31d0aeb0dd4f8789501/packages/sinuous/observable/src/observable.js#L83-L84

**Comment by kethan** [comment]
> just be careful with `ob.name === "i" || ob.name ==="data"`
> `i` is the minified name I imagine but this can change from build to build, it's what the JS minifier chooses at build time.
> 
> The observable function also has a `.$o` prop set to true. It's safer to use . that I think.
> https://github.com/luwes/sinuous/blob/529d718f1132929c3001c31d0aeb0dd4f8789501/packages/sinuous/observable/src/observable.js#L83-L84

How to access? s2.c.count.$o?

**Comment by luwes** [comment]
yup that should work
