### ISSUE TITLE
How ready is this?

### ISSUE THREAD

**Issue by krankur** [luwes/sinuous#39]
Just the kind of simplicity and ergonomics that I was looking for in a JS library. However I have a few questions:
- Can this be used in production?
- If not, what features are missing?
- Is there a roadmap?

**Comment by luwes** [comment]
good timing @krankur 👍 I think it's almost time to set up a v1.0.0 roadmap.

I'm pretty confident in the state of Sinuous as of now, test coverage is good but like in all software projects there will be some bugs here and there. 

- I would recommend to wait for v1 to use it in production just to be safe.
- the basics are there I think, you can see in the several examples including the TodoMVC that it's very use-able. 
- I'll have a brainstorm soon about what checkmarks should be checked, if you have any feedback or wishes please let me know.

**Comment by luwes** [comment]
Closing in favor of https://github.com/luwes/sinuous/milestone/1
