### ISSUE TITLE
I need some help with my benchmark implementation

### ISSUE THREAD

**Issue by ts-thomas** [luwes/sinuous#50]
I want to provide a new test category where the performance of dealing with internal data comes back for libraries like surplus and sinuous. But I'm stuck on one specific step. Maybe you see the issue promptly.

This is the test implementation for your lib: https://github.com/nextapps-de/mikado/blob/master/bench/test/sinuous/internal.html
This is the specific line which fails: https://github.com/nextapps-de/mikado/blob/master/bench/bench.js#L424

I also tried to pass store reference to this method and apply like `var data = items(); data[0].title = "foo"; items(data);` but without luck, the changes are not rendered.

Would be really nice if I could solve this.

**Comment by luwes** [comment]
@ts-thomas to make properties reactive in Sinuous `template`, the `o` function has to be used instead of the `t`. For example making title reactive:

```js
        const Row = template(() => html`
            <section data-id=${ t('id') } data-date=${ t('date') } data-index=${ t('index') }>
                <div class=${ t('classname') } style="padding-right: 10px;">
                    <div class="title" textContent=${ o('title') }/>
                    <div class="content" textContent=${ t('content') }/>
                    <div class="footer" textContent=${ t('footer') }/>
                </div>
            </section>
        `);
```

Then later one can set the new value like so `data[0].title = "foo";`
The title prop will have been set with `defineProperty`.

---

On a side note Sinuous performs slightly better when not using the `textContent` properties but just write it like in html. It uses `CharacterData.data` under the hood whenever it can.

```js
        const Row = template(() => html`
            <section data-id=${ t('id') } data-date=${ t('date') } data-index=${ t('index') }>
                <div class=${ t('classname') } style="padding-right: 10px;">
                    <div class="title">${ o('title') }</div>
                    <div class="content">${ t('content') }</div>
                    <div class="footer">${ t('footer') }</div>
                </div>
            </section>
        `);
```

Hope this helps and works!

**Comment by ts-thomas** [comment]
Cool thanks, I will try it later today

**Comment by luwes** [comment]
FYI one extra optimization for Sinuous is to compile the tagged templates to `h` function calls with `sinuous/babel-plugin-htm`. 

`import { html } from 'sinuous`;` is the runtime version.

it uses a modified version of https://github.com/developit/htm under the hood.
worth a look how they parse the templates, minimal regex and no eval usage.

**Comment by ts-thomas** [comment]
It works promptly, and the performance also comes back :)
https://github.com/nextapps-de/mikado/blob/master/bench/README.md#data-driven-internal
