### ISSUE TITLE
Request: explicit dependency observable

### ISSUE THREAD

**Issue by theSherwood** [luwes/sinuous#54]
Hi @luwes et al,

First, thank you for sinuous. I haven't put it to hard use yet, but the tinkering I've done with your library has been a lot of fun. I'm looking forward to getting a lot of use out of it. 

Looking at sinuous/observable, I didn't see any option for explicitly setting dependencies for an observable or computed function. S.js has `S.on(...)`, for example. I find having that option pretty handy. And since you seem to favor global functions over dot notation, I thought `watch([deps], fn)` could work as an api.

Let me know if something like this falls within your vision for sinuous!

Best of luck and thanks again.

**Comment by luwes** [comment]
I'll have a look at this soon. I think it could be a good fit.

**Comment by theSherwood** [comment]
As a follow up to this: the explicit version of `subscribe(...)` could be `on(...)` while the explicit version of `computed(...)` could be `watch(...)`. That seems fairly semantic to me. What do you think?

**Comment by luwes** [comment]
that would be good naming 👍 

just not fully sure it the additions are worth it. I checked S.js and its explicit  `S.on()` method is almost an alias for `S`.

Something like this would already work as a small utility function:

https://codesandbox.io/s/sinuous-observable-y6rm3

```js
import { observable, subscribe } from "sinuous/observable";

const name = observable("World");
setTimeout(() => name("Dude"), 2000);

function on(obs, fn) {
  obs = [].concat(obs);
  subscribe(() => {
    obs.forEach(o => o());
    fn();
  });
}

on([name], () => {
  console.log(999);
});

```

**Comment by theSherwood** [comment]
That makes sense. I put together an example of `on` and `watch` in case anyone is curious about this.
https://codesandbox.io/s/sinuous-explicit-observables-mxupr

```
import { subscribe, computed } from "sinuous/observable";

function on(obs, fn) {
  obs = [].concat(obs);
  return subscribe(() => {
    obs.forEach(o => o());
    fn();
  });
}

function watch(obs, fn, seed) {
  obs = [].concat(obs);
  return computed(() => {
    obs.forEach(o => o());
    return fn();
  }, seed);
}
```

The only thing these functions are missing is a way to not react to any observables in `fn` arguments by default. In the sandbox above, I explicitly use `sample` from `sinuous/observable`. But the semantics of `on` and `watch` indicate that they ought to do it by default.

For example:
```
const o1 = observable(...)
const o2 = observable(...)

const c1 = watch([o1], () => console.log(o2()))
```
Currently, that will cause `c1` to update on changes in both `o1` and `o2`. To my mind, having explicit dependencies should mean those are the **only** dependencies. But as things currently stand, in order to update only on changes to `o1`, we must use `sample` on `o2`.
```
const o1 = observable(...)
const o2 = observable(...)

const c1 = watch([o1], () => console.log(sample(o2)))
```
So I think these `on` and `watch` functions could be improved upon.

**Comment by luwes** [comment]
Cool! 🙂 

Good points, didn't think that the function should be sampled.
This should do it, https://codesandbox.io/s/sinuous-explicit-observables-bulon

The missing piece was to put the sample around the `fn` in the new methods.

**Comment by theSherwood** [comment]
Awesome! That's working great. Thanks for fixing that!

**Comment by luwes** [comment]
`on` was added

```js
/**
 * Statically declare a computation's dependencies.
 *
 * @param  {Function|Array}   obs
 * @param  {Function} fn - Callback function.
 * @param  {*} [seed] - Seed value.
 * @param  {boolean} [onchanges] - If true the initial run is skipped.
 * @return {Function} Computation which can be used in other computations.
 */
export function on(obs, fn, seed, onchanges) {
  obs = [].concat(obs);
  return computed((value) => {
    obs.forEach((o) => o());

    let result = value;
    if (!onchanges) {
      result = sample(fn, value);
    }

    onchanges = false;
    return result;
  }, seed);
}
```
