### ISSUE TITLE
A `render` function or mode

### ISSUE THREAD

**Issue by luwes** [luwes/sinuous#58]
I think this might be possible similarly to lit-html where they use the string part of the tagged template as a cache key and always return the same Node but update the dynamic parts on each render.

Sinuous could have a mode that instead of rendering once and update fine grained with the help of computeds, update with a render function which would also only create DOM once but update the dynamic values if they change with the `api.insert` and `api.property` calls.

All the logic is pretty much there from `sinuous/template`.
The only challenge is to create a unique key from the hyperscript calls that could be used for caching the DOM tree and getting the dynamic template fields/holes.

**Comment by mrjjwright** [comment]
so this was released yesterday right?   When would you choose to use `rhtml` over a normal component `html`?

**Comment by luwes** [comment]
good question. it comes with a slight overhead of about 1kB gzip. it's basically `sinuous/template` + `sinuous/render`. The render module depends on template.

it's quite a different approach but I think there's still some merit where both can work in tandem. 

one benefit the render module (`rhtml`) comes with is that it uses cloning (Element.cloneNode(true)) under the hood if the static parts of the template are the same so if you have lots of repeating html structure it would be faster with the render module.

personally I would not start using it right away until you run in some issues caused by excessive DOM changes, even then there is also `sinuous/template` on its own and `sinuous/memo` can also help with caching.

this approach also allows someone to completely discard of the observables concept and just use the repeating render function with primitive values. I wouldn't do this myself but it's possible.

**Comment by mrjjwright** [comment]
Ok thanks for the explanation!!  I think I get it!  Actually could be super useful for certain functional components that shouldn’t ever be reactive to observables but need to render with holes very efficiently on server or client.

**Comment by luwes** [comment]
implemented in this PR https://github.com/luwes/sinuous/pull/59
available as an experimental module, https://github.com/luwes/sinuous/tree/master/packages/sinuous/render

saying experimental but it has a decent test coverage of 99% with lots of tests borrowed from lit-html.
