### ISSUE TITLE
Fav CSS approach

### ISSUE THREAD

**Issue by mrjjwright** [luwes/sinuous#63]
What is your recommendation when building a larger app: inline styles or css or do you have a fav css-in-js solution in the spirt of Sinuous?

**Comment by luwes** [comment]
I'm still a bit old school in this 😄. I prefer external CSS stylesheets with classes. I've heard some good things of css-in-js but I have yet to try it out. 

https://github.com/cristianbote/goober seemed like a nice one, good size!

**Comment by mrjjwright** [comment]
That’s the exact one I was considering!  It supports a h like api that I guess could be plugged into sinuous.

**Comment by mrjjwright** [comment]
Meaning styled sinuous divs.

**Comment by mrjjwright** [comment]
I didn't get the styled component part of goober to work with Sinuous but it's probably a mismatch anyhow.  But just generating the css in JS via goober's css api is working great:

```javascript
const className = css`
display: flex;
width: 100px;
`;

const component = html`
    <div class=${className}>Yo</div>`;
```

...and saves the needs for managing external CSS if you are super JS centric like me.

**Comment by mrjjwright** [comment]
Also if you are looking for a tiny classnames util to concatenate classnames: https://github.com/TroyTae/one-spaces

**Comment by luwes** [comment]
I've used this one in the past too, very small https://github.com/lukeed/obj-str
yes, not sure about the setPragma option in Goober, maybe it's only for vdom. there's some mention of it in the description.

thank you for your donation, I appreciate it!

**Comment by mrjjwright** [comment]
I love his stuff!  Thanks!
