### ISSUE TITLE
Typing questions

### ISSUE THREAD

**Issue by mrjjwright** [luwes/sinuous#65]
Shouldn't:

https://github.com/luwes/sinuous/blob/141519e5df785f6b046bae70fc09b583e92c6378/packages/sinuous/observable/src/index.d.ts#L8

be typed as 

```javascript
export const observable: ObservableCreator<any>;
```

or am I missing something?  I can't get this simple line to compile. 

![image](https://user-images.githubusercontent.com/4343/73611390-a692a880-459e-11ea-95fe-bb9f3d9d7d24.png)

**Comment by luwes** [comment]
hmm, that should be possible. will take a look at this.

**Comment by luwes** [comment]
you were right, just pushed a commit with your suggestion and released in 0.23.2.

**Comment by mrjjwright** [comment]
Working great, thanks so much for the prompt fix, I am rolling!
