### ISSUE TITLE
Nested transactions throw error

### ISSUE THREAD

**Issue by mrjjwright** [luwes/sinuous#66]
https://github.com/luwes/sinuous/blob/7c1749126c7ed993bdc1841adcb6744dd0fa465f/packages/sinuous/observable/src/observable.js#L61

A nested transaction (another transaction called during this callback), if you intend to allow them, will throw a `Cannot read property 'forEach' of undefined` on line 65 because the queue is set to undefined by the nested tx after it runs.   Perhaps set a flag and skip all this in nested txs or something?

![image](https://user-images.githubusercontent.com/4343/73615142-a4424580-45c2-11ea-8c19-7c34e3991152.png)

**Comment by luwes** [comment]
ah yes thanks, good find! will look into this soon.

**Comment by mrjjwright** [comment]
thanks!
