### ISSUE TITLE
How to pass data from map to observable

### ISSUE THREAD

**Issue by darekmeco** [luwes/sinuous#7]
In Event handler function I need both event and item
Then I have:

```
onclick = o(clicked);
```
```
clicked = (e, a) => {
    console.log('e:',e);
    console.log('a:',a);
    e.preventDefault();
  }
```
```
${map(this.categories, (item) => this.html`<li id=${item.id}><a class=${this.activeClass(item)} onclick="${this.onclick}" href="${item.id}">${item.name}</a></li>`)}
```
How to pass item to event handler with observable?

I can only:
```
onclick="${() => () => this.clicked(event, item)}
```
Thanks

**Comment by luwes** [comment]
This should do it:

```js
	<li onclick=${c => (c = onclick()) && (e => c(e, item))}>
		${item.name}
	</li>
```

Here's a codesandbox
https://codesandbox.io/s/sinuous-advanced-event-handler-jks74

I hope to clean this event syntax up soon
Here's the issue for that #3

**Comment by luwes** [comment]
Update:

Looks like this works too

`onclick=${() => event => onclick()(event, item)}`

a bit cleaner and removing still works with `onclick(false)`

**Comment by darekmeco** [comment]
Thank you for your explanation

**Comment by luwes** [comment]
Updated example with v0.10.0, this was a breaking change.
Regular event handler functions don't need the extra wrapping closure anymore.
https://codesandbox.io/s/sinuous-advanced-event-handler-jks74
