### ISSUE TITLE
A simple routing example?

### ISSUE THREAD

**Issue by kethan** [luwes/sinuous#70]
Hi can you show me a minimal routing example using sinuous components?

**Comment by luwes** [comment]
Thanks for your question @kethan! I've yet to build a Sinuous app with a router.
I've used https://github.com/visionmedia/page.js in the past which should be quite easy to integrate into a Sinuous app.

The gist of it; a switch type of condition in the root of your app, much like
https://github.com/luwes/sinuous/issues/6#issuecomment-575921372 or even better https://github.com/luwes/sinuous/issues/56#issuecomment-578367692. So it would have one observable looking at the current route url and when the route changes it would swap the components under the condition in the root of your app.

Hope this helps.

**Comment by kethan** [comment]
Not much clear. But I will try to understand.

**Comment by kethan** [comment]
Anything simpler ?

**Comment by mindplay-dk** [comment]
@kethan 

> Anything simpler ?

You can find an extremely simple example of client-side routing in the official [TodoMVC example](https://github.com/luwes/sinuous-todomvc/).

In [lines 72-74](https://github.com/luwes/sinuous-todomvc/blob/6b4d6d435f54d173ebb89968e2f7d16281f826a3/src/index.js#L72-L74), a simple `hashchange` listener is bootstrapped to update the view:

```js
const updateView = () => filter(location.hash.slice(2) || 'all');
window.addEventListener('hashchange', updateView);
updateView();
```

That last call to `updateView()` initializes the route when the program launches - the call to `filter` is a call to an observable declared [here](https://github.com/luwes/sinuous-todomvc/blob/master/src/controller.js#L9), which is how the change propagates to the view.

In [Lines 59-61](https://github.com/luwes/sinuous-todomvc/blob/6b4d6d435f54d173ebb89968e2f7d16281f826a3/src/index.js#L59-L61), the routing is triggered by plain `<a>` tags:

```html
<li><a class=${() => cx({ selected: filter() === 'all' })} href="#/">All</a></li>
<li><a class=${() => cx({ selected: filter() === 'active' })} href="#/active">Active</a></li>
<li><a class=${() => cx({ selected: filter() === 'completed' })} href="#/completed">Completed</a></li>
```

This example is just static routes, for which `location.hash.slice(2)` is all the "parsing" necessary. 😉

You can build on that concept easily by doing slightly more to match and parse parameterized routes here - there's page.js as mentioned in the reply above, and probably 100 other frameworks for this, but if you want to keep it simple, you could try a "router" like this:

```js
const routes = {
  products: /^products\/(?<id>\d+)$/,
  details: /^products\/(?<id>\d+)\/details$/,
  users: /^users\/(?<name>\w+)$/,
}

function resolve(path) {
  for (const route in routes) {
    const result = path.match(routes[route]);
    if (result) {
      return { ...result.groups, route };
    }
  }
}
```

You can learn about named capturing groups in regular expressions [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges).

Apply the `resolve` function to the path (`location.hash.slice(2)`) and a path like e.g. `users/john` will resolve to `{name: "john", route: "users"}`, and you can write `if/else` or a `switch` statement to decide based on `route` which component to use, how to pass parameters like `name`, and so on.

**Comment by kethan** [comment]
Perfect thanks.

**Comment by mindplay-dk** [comment]
You're welcome. 🙂

Here's a [working example](https://codesandbox.io/s/sinuous-router-g2eud) for others who come across this thread.

Maybe @luwes can confirm whether this example is sound? I'm not 100% sure if the way I'm doing this really leads to granular updates of the view itself or just the entire `App`?

I am still just learning Sinuous myself and trying to wrap my head around the reactivity aspect, which still seems a bit like magic to me... This is very different from React, but I have a really good feeling about this already! 😀

**Comment by luwes** [comment]
Thanks for putting together a routing example @mindplay-dk! This LGTM.
The updates are granular, only the h2 tag is updated.

**Comment by kethan** [comment]
@mindplay-dk Amazing work it's very clear now. @luwes thanks for this great library.

**Comment by luwes** [comment]
Added to the readme examples so closing here.
