### ISSUE TITLE
'contenteditable' in place of 'contentEditable'

### ISSUE THREAD

**Issue by theSherwood** [luwes/sinuous#71]
I noticed that, using tagged templates at least, `contenteditable` seems to do nothing while `contentEditable` sets the correct property on the node. I don't know if there are other attributes that are working this way or not. But it seems inconsistent with the `onclick` and `oninput`. Thought I ought to make you aware.

https://codesandbox.io/s/sinuous-contenteditable-elq81

**Comment by luwes** [comment]
thanks for mentioning, it's expected. Sinuous sets JS properties, not attributes.

https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onclick
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/contentEditable

JSX or React I'm not sure kinda changed some syntax in this regard. With Sinuous I tried to just stay as close to the original naming.

**Comment by theSherwood** [comment]
Oh, of course. That makes sense.
