### ISSUE TITLE
What is a tag action?

### ISSUE THREAD

**Issue by mrjjwright** [luwes/sinuous#72]
What exactly is a tag action?  Is it an effect that runs to set an attribute on an html element?  Why is it recorded and why a global array of recorded actions.  Trying to understand template and data modules better.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/4343/74771873-32b5f880-524c-11ea-8bfb-3cee0fd3258f.png">

**Comment by mrjjwright** [comment]
Feel bad, no need to actually answer this.   Don't want to give you some explanation task but feel free to add something if the spirit leads.

**Comment by luwes** [comment]
No worries, happy to answer.

When a template is created the `o` and `t` template tags are associated with an element and an action that either calls the internal `api.property` or `api.insert` method. For setting properties on the element or adding content to the element. 

The actions are saved for subsequent template clones, on each clone they're looped through and called on an element in the same position than the original element.

The `o` tag adds proxy like behavior to the object literal passed to the template. When setting the property it will call the associated action.

Hope this makes sense a bit.

**Comment by mrjjwright** [comment]
absolutely does, fantastic explanation.  this is an intriguingly simple little rendering mechanism.

**Comment by mrjjwright** [comment]
I don't get the difference between `template` and `fill`, they seem exactly the same.
