### ISSUE TITLE
Doesn't parse entities

### ISSUE THREAD

**Issue by mindplay-dk** [luwes/sinuous#79]
I'm trying to write something [here](https://codesandbox.io/s/sinuous-date-picker-ye0oe) and noticed the entities aren't getting parsed.

For example, `&#9654;` just comes out as the text rather than the Unicode symbol.

I think *named* entities aren't possible in XML/JSX, as they're an HTML feature, but I'm pretty sure encoding numeric entities ought to be possible?

Is that also not supported by the original HTM lib?

(By the way, I mean for this to turn into another example you might consider adding - a custom date-picker is an interesting example that I try to replicate in every library I try, for comparison, as it presents some pretty interesting challenges. At the moment, it doesn't yet communicate it's value back to a parent - do you have an example of the Sinuous way to implement custom inputs and form elements? What's a good way to communicate back and forth? Maybe pass an observable for the value via props?)

**Comment by mindplay-dk** [comment]
To others running into this:

This ins't supported either by the original HTM library or by JSX itself.

The solution is to insert literal Unicode characters rather than escape-codes.

Closing this issue. 🙂

@luwes my [date-picker example](https://codesandbox.io/s/sinuous-date-picker-ye0oe) is now functional - simply passing an observable seemed to make sense, as opposed to the usual `value` and `onInput` pair we'd use in most other engines? Seems to make a lot of sense for custom controls, so the control itself isn't dealing with it's own value state, which can instead be directly bound by the parent component.

**Comment by luwes** [comment]
great you figured it out quickly. the date picker is really cool, I'll add it to the examples on the readme page! I think that makes sense with passing an observable and easier 👍
