### ISSUE TITLE
sinuous and swiss ?

### ISSUE THREAD

**Issue by darekmeco** [luwes/sinuous#8]
Hi, should I mix sinuous with your swiss, for component managment ? Is this goog idea ?, I can make components with sinuos itself, but swiss has a great element().

**Comment by luwes** [comment]
@darekmeco yes, I think this should work pretty well.
I was hoping they would be used together.

Here's a simple example. 
https://swiss.netlify.com/fixtures/renderers/sinuous/

Documentation is still on the todo list :)

**Comment by darekmeco** [comment]
Thank you for this example, this is exactly what I looking for.
