### ISSUE TITLE
Effects

### ISSUE THREAD

**Issue by mindplay-dk** [luwes/sinuous#80]
Is there any such thing as effects?

Specifically, I need to attach an event handler to the document root, so my component can respond to clicks outside the component instance. (e.g. a custom drop-down that needs to close.)

I could just attach the handler itself from the component function, since that only runs once - but how would I know when the component gets removed, so I can clean up the listener?

Or is there another (more Sinuous) way to solve this problem?

**Comment by luwes** [comment]
Yes this is built into the reactive system. `cleanup(fn)` from `sinuous/observable` will run the callback right before the computation updates or is disposed. 

The S.js docs have a good explanation around this, see https://github.com/adamhaile/S#scleanupfinal--code. It works the same in Sinuous.

---

Alternatively it's also possible to listen for an element's `connected` and `disconnected` events via this small utility https://github.com/luwes/disco

**Comment by mindplay-dk** [comment]
Thanks, yeah `cleanup` looks like the way to go.

The S.js [docs](https://github.com/adamhaile/S#scleanupfinal--code) for `cleanup` mentions a `final` boolean - is this supported by `sinuous/observable` as well? It isn't mentioned in the [documentation](https://github.com/luwes/sinuous/tree/master/packages/sinuous/observable#cleanup) for that function and doesn't seem to appear [in the code](https://github.com/luwes/sinuous/blob/master/packages/sinuous/observable/src/observable.js#L251)?

Without the `final` boolean, how can I tell if the call is intended to clean up after an update vs finally cleaning up after the component instance? (The latter is what I'm after.)

**Comment by mindplay-dk** [comment]
Ah, I think I found the answer in the [S.js docs](https://github.com/adamhaile/S#cleaning-up-stale-side-effects):

```
const onClickHandler = e => doSomething();
el.addEventListener('click', onClickHandler);
S.cleanup(() => el.removeEventListener('click', onClickHandler));
```

So the idea is to clean up after any side-effects with every update - in this case, to add and remove event-listeners with every update.

That'll work - though I'm not completely sure I understand why that's necessary? 🤔

**Comment by ryansolid** [comment]
I think it is important to recognize that the component itself is probably a computed itself, so a cleanup method there also works. Basically the scenarios where `final` matter are strange ones where you've taken management on to yourself.

Like if you have a component that is conditionally rendered (ie it isn't always on the page) but there as a result of say navigation. At the time of the condition changing your are creating your component under a reactive context. Now that context stays for the life of the component since re-evaluating would wipe out your component completely and possibly re-create it. Instead your component creates its own computeds that update on their own schedule. So you can just write `cleanup` methods whereever you want and they will evaluate whenever that context does.

So in your component a top level `cleanup` should last the life of the component instance. One inside a computed lasts until that computed re-evaluates. The final flag actually isn't guarenteed final. It just means that your context is nested so the parent has also been blown away. But for most cases unless you are doing nested cleanup on the parent you shouldn't need it.

**Comment by mindplay-dk** [comment]
> I think it is important to recognize that the component itself is probably a computed itself, so a cleanup method there also works.

ahaaaaah 👀

Man, the more I understand this, the more it just makes sense. 😀

**Comment by luwes** [comment]
thanks for explaining in more detail @ryansolid!

indeed, Sinuous doesn't have the `final` flag. looking a bit at the source code of S.js. `final` is set to true when cleanup is done via the `dispose()` function which is given to you from defining a `root((dispose) => { })`.

I don't think it would be needed for your use case.

Here's a quick example extended from your date picker how the cleanup might work.
https://codesandbox.io/s/sinuous-date-picker-he9iu

**Comment by mindplay-dk** [comment]
Alright, so here's a working pop-up date-picker. 😀

https://codesandbox.io/s/sinuous-date-picker-thxdt

Man, this was so *easy* - the fact that you just *have* the actual DOM elements at the time of creation, it's so much simpler than refs and whatnot. Using observables for the input and picker value means that state just propagates and things work immediately without any extra wiring. This makes for *excellent* component composition.

The only thing I'm not completely sure about is this:

```js
  subscribe(() => {
    value()
    isOpen(false)
  })
```

This seems a bit magical. I mean, it's all magical, in the sense that subscriptions are always automatically established via signals when you read something, but... I don't know, maybe it's the syntax?

Something like this would seem more meaningful to me:

```js
  subscribe(value, () => {
    isOpen(false)
  })
```

To me, this says, "subscribe to value", whereas the other syntax just says "subscribe"... to what? And then you read through the body of the function and hopefully understand the side-effect of reading an observable. It's a bit cryptic and initially I didn't understand what I was subscribing to.

But my use-case is a bit weird, I think? I don't actually need the value, I just want to know when the value changes, because that should close the popup.

Is there a less confounding way to achieve this?

Maybe a plain `onChange` callback in the date-picker itself would make more sense?

Just kinda seems like we have this excellent facility for broadcasting state changes, and I might prefer not to go around it and maybe leverage it instead..?

**Comment by luwes** [comment]
I'm considering adding an `on` function which would just do that.
Based on https://github.com/adamhaile/S#sonsignal-val--code-seed-onchanges

check out https://github.com/luwes/sinuous/issues/54#issuecomment-575916485
that's pretty much what's needed. I recently ran into a case myself where I needed this.

```js
export function on(obs, fn) {
  obs = [].concat(obs);
  let subscribed;
  subscribe(() => {
    obs.forEach((o) => o());
    if (subscribed) sample(fn);
  });
  subscribed = true;
}
```

will only run on changes, not on the initial run.

**Comment by mindplay-dk** [comment]
What does `sample(fn)` accomplish here?

Isn't `sample` just a way to read the current value of an observable without tracking it's usage?

How is it different from just `fn()`?

**Comment by luwes** [comment]
that got spawned from this comment
https://github.com/luwes/sinuous/issues/54#issuecomment-575903947

I think it makes sense, since you're only care about the changes of the observables you passed as the first argument.
