### ISSUE TITLE
Demo: 7 GUIs

### ISSUE THREAD

**Issue by theSherwood** [luwes/sinuous#85]
Hi @luwes,
I'm putting together a site with some examples of [7 GUIs](https://eugenkiss.github.io/7guis/) implemented in various frameworks. Here's a [codesandbox](https://codesandbox.io/s/github/theSherwood/7_GUIs/tree/master/sinuous) with 7 Guis implemented in Sinuous. I thought you might have use for this in your demos.

**Comment by luwes** [comment]
Wow this is great! Yes, if you like we can add it to the readme.
Great resource for other people trying Sinuous out.

**Comment by theSherwood** [comment]
#87 Here's a pull request!
