### ISSUE TITLE
Sinuous requires a itself as a peer dependency

### ISSUE THREAD

**Issue by heyheyhello** [luwes/sinuous#96]
Hello!

I receive this warning during the npm install:

```
npm WARN sinuous@0.27.0-beta.3 requires a peer of sinuous@>=0.6.0 but none is installed. You must install peer dependencies yourself.
```

I was wondering if you could clarify the why the package.json needs to refer to itself?

It was introduced here: https://github.com/luwes/sinuous/commit/87d4b583fe8821bf911ee959965964bf3864e364

Thanks ☀️

**Comment by luwes** [comment]
@heyheyhello thanks for the feedback! 

it's a good point, it's probably not necessary. 

I added it because the submodules like `sinuous/map` require that as a peer dependency.

**Comment by luwes** [comment]
should be good in beta 4 ;)
