### ISSUE TITLE
Lazy component?

### ISSUE THREAD

**Issue by kethan** [luwes/sinuous#97]
How to write a lazy component?

something like this...
```js
let Lazy = () => {
  setTimeout(() => {
    return html`<div>Hello World</div>`
  }, 3000);
};

```

**Comment by heyheyhello** [comment]
Return an empty fragment (so the parent of Lazy() can mount something) and trigger an observable subscription in the html`` call. Then, whenever you want, update the observable and the subscription will cause the render.

```js
const Lazy = () => {
  const content = o('')
  setTimeout(() => content(html`<div>Hello World</div>`), 3000)
  return html`${content}`
```

(Haven't tested this because I'm posting from my phone)
