### ISSUE TITLE
Performance of map/mini

### ISSUE THREAD

**Issue by blankhart** [luwes/sinuous#98]
The `map/mini` algorithm performs very badly in some cases, such as the "swap rows" benchmark in the JS frameworks benchmark.  

It should be possible to reproduce the performance hit by just substituting the `map` import to use `map/mini` in the benchmark. On my machine, the result for the "swap rows" task goes from about 1.06x to about 8.65x (deep red).

It is not hard to see why after inspecting the algorithm.  Effectively, the result of swapping the second node with the penultimate node is to replace almost every DOM node in the thousand-item list, one by one.

The diff-and-patch algorithm on which it is based has the same authorship as `snabbdom`, but has a number of differences from the algorithm currently used by that library (see [`updateChildren`](https://github.com/snabbdom/snabbdom/blob/af596d4a42252a20e93d5e351f5e937632e10eb8/src/snabbdom.ts#L202)).

As relevant to "swap rows," the principal difference is that the `snabbdom` algorithm searches for moves and diffs the list from both ends, rather than only forward. So it discovers that the second and penultimate nodes have been swapped much sooner.

I played with it a little and think that adapting the the current `snabbdom` algorithm to `sinuous` would look something like [this gist](https://gist.github.com/blankhart/a36b64cee6b3e398f32725ee447c14e1).  Using this version of `map` brings the "swap rows" result back down to about 1.08x.  

It is not quite as tiny as the current `map/mini` but potentially could be golfed down if that is important.  I haven't spent a lot of time thinking through the details or exposed this version to tests.

**Comment by luwes** [comment]
Wow thank you for this! it's funny I was just looking into the diffing algorithms, testing which ones performed best with least amount of operations.

I added your version to the benchmark and it's already the best.
https://github.com/luwes/js-diff-benchmark

**Comment by luwes** [comment]
Fixed in #102
